---
title: How to recruit volunteers
hero_image: images/Volunteers_celebrating.png
description: This course will focus on supporting those involved in managing and running a Dojo to recruit volunteers.
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Reflect
- title: Role descriptions
- title: Promote
- title: Resources to promote
- title: Respond
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: What next?
